{% set version = "0.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mime
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mime_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mime/mime_{{ version }}.tar.gz
  sha256: 2ccf97d2940a09539dc051c7a9a1aee90ef04b34e9bc6c0b64b4435fb3c2fa80

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('mime')"           # [not win]
    - "\"%R%\" -e \"library('mime')\""  # [win]

about:
  home: https://github.com/yihui/mime
  license: GPL
  summary: Guesses the MIME type from a filename extension using the data derived from /etc/mime.types
    in UNIX-type systems.
  license_family: GPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: mime
# Type: Package
# Title: Map Filenames to MIME Types
# Version: 0.7
# Authors@R: c( person("Yihui", "Xie", role = c("aut", "cre"), email = "xie@yihui.name", comment = c(ORCID = "0000-0003-0645-5666")), person("Jeffrey", "Horner", role = "ctb"), person("Beilei", "Bian", role = "ctb") )
# Description: Guesses the MIME type from a filename extension using the data derived from /etc/mime.types in UNIX-type systems.
# Imports: tools
# License: GPL
# URL: https://github.com/yihui/mime
# BugReports: https://github.com/yihui/mime/issues
# LazyData: TRUE
# RoxygenNote: 6.1.0
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2019-06-11 19:49:18 UTC; yihui
# Author: Yihui Xie [aut, cre] (<https://orcid.org/0000-0003-0645-5666>), Jeffrey Horner [ctb], Beilei Bian [ctb]
# Maintainer: Yihui Xie <xie@yihui.name>
# Repository: CRAN
# Date/Publication: 2019-06-11 20:10:03 UTC
